- subt_ign/src/VisibilityRfModel.cc
This changes the color scheme from Red --> Green to Green --> Red.
> Change colors for comms visualization.

- docker/download_models.sh
- subt_ign/include/subt_ign/VisibilityTable.hh
- subt_ign/src/ConnectionHelper.cc
- subt_ign/src/ConnectionHelper.hh
- subt_ign/src/ConnectionValidatorPrivate.cc
> Cave Type A tiles

- subt_ros/launch/validator_topics.launch
> Fix validator to use TF2

- submitted_models/robotika_kloubak_sensor_config_1/specification.md
Here is updated Kloubak K2 specification with links to some data and videos from @tajgr
> Robotika Kloubak K2 - update specification

- subt_ign/worlds/cave_circuit_practice_01.sdf
To test:
```
ign launch -v 4 cave_circuit.ign circuit:=cave worldName:=cave_circuit_practice_01 robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1 
```
Set the pose of the X1 near fall 1:
```
ign service -s /world/cave_circuit_practice_01/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position { x: 258 y:-99  z: -24.4}'
```
near fall 2:
```
ign service -s /world/cave_circuit_practice_01/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position { x: 84 y:-263 z:0} orientation {z: -1.0 w: 1}'
```
near fall 3
```
ign service -s /world/cave_circuit_practice_01/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: …
```
> Add falling rocks to cave practice circuit 1

- subt_ign/launch/cave_circuit.ign
- subt_ign/launch/cloudsim_sim.ign
- subt_ign/worlds/cave_circuit_practice_02.sdf
To test:
```
ign launch -v 4 cave_circuit.ign circuit:=cave worldName:=cave_circuit_practice_02 levels:=false robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1
```
Set the pose of the X1 near fall 1:
```
ign service -s /world/cave_circuit_practice_02/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position { x: 308 y:195  z: -22.8}'
```
Set the pose of the X1 near fall 2:
```
ign service -s /world/cave_circuit_practice_02/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position { x: 768 y:-24  z: -47}'
```
Set the pose of the X1 near fall 3:
```
ign service -s /world/cave_circuit_practice_02/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype …
```
> Add falling rocks to cave practice circuit 2

- subt_ign/launch/cave_circuit.ign
- subt_ign/worlds/cave_circuit_practice_03.sdf
To Test:
```
ign launch -v 4 cave_circuit.ign circuit:=cave worldName:=cave_circuit_practice_03 levels:=false robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1
```
Set the pose of the X1 near fall 1 (local obstacle):
```
ign service -s /world/cave_circuit_practice_03/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position {x:364 y:223 z:0.5}'
```
Set the pose of the X1 near fall 2  (local obstacle):
```
ign service -s /world/cave_circuit_practice_03/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position {x:835.5 y:127.7 z:20.2}'
```
Set the pose of the X1 near fall 3 (global obstacle):
```
ign service -s /world/cave_circuit_practice_03/set_pose /set_pose …
```
> Add falling rocks to cave practice 3

- submitted_models/robotika_x2_sensor_config_1/launch/spawner.rb
Note, that this is old configuration number 1
> Fix robotika_x2_sensor_config_1 speed limits for original X2 robot

- submitted_models/robotika_kloubak_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/robotika_kloubak_sensor_config_1/model.sdf
Resolves the following issues:
- The front and rear odometry topics on the Robotika Kloubak model are incorrectly mapped on the Ignition topic side for transport to the ROS side.
- The front and rear cameras are partially obstructed by the mesh.
> Robotika Kloubak model updates

- subt_ign/src/GameLogicPlugin.cc
- subt_ign/worlds/cave_circuit_practice_01.sdf
- subt_ign/worlds/cave_circuit_practice_02.sdf
- subt_ign/worlds/cave_circuit_practice_03.sdf
This will log information whenever a robot enters or leaves a performer detectors. Example output:
```
- event:
time_sec: 36
detector: performer_detector_staging
robot: X1
state: enter
pos:
x: -2.99869
y: 2.67071
z: 0.137346
- event:
time_sec: 45
detector: performer_detector_staging
robot: X1
state: exit
pos:
x: 3.00125
y: 0.842902
z: 0.183054
```
> Start of an event logger

- submitted_models/explorer_r2_sensor_config_1/launch/spawner.rb
- submitted_models/explorer_r2_sensor_config_1/launch/vehicle_topics.launch
Fixed a typo in `vehicle_topics.launch` that prevented Ignition to ROS transport.
Added reduced velocity and battery life limits to the model until validation data is provided.
> Explorer R2 Issues

- subt_ign/src/GameLogicPlugin.cc
Publishes the remaining artifact reports on `/subt//subt/artifact_reports_remaining`.
> Add artifact report publisher

- subt_ign/src/GameLogicPlugin.cc
Change behavior to publish artifacts remaining at 1Hz.
> Periodically send artifact remaining

- subt_ign/launch/cloudsim_sim.ign
Requires: https://github.com/ignitionrobotics/ign-launch/pull/40
> Limit maximum number of websocket connections

- submitted_models/explorer_ds1_sensor_config_1/launch/spawner.rb
- submitted_models/explorer_ds1_sensor_config_1/specifications.md
- submitted_models/explorer_r2_sensor_config_1/launch/spawner.rb
- submitted_models/explorer_r2_sensor_config_1/specifications.md
New test links are added to specifications.md and motion parameters in spawner.rb are changed according to specifications.md.
These pull request is for both DS1 and R2.
> New validation links added to specifications.md from Explorer

- submitted_models/marble_hd2_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_hd2_sensor_config_1/model.sdf
- submitted_models/marble_hd2_sensor_config_1/specifications.md
- submitted_models/marble_hd2_sensor_config_1/test_gimbal.sh
- submitted_models/marble_husky_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_husky_sensor_config_1/model.sdf
- submitted_models/marble_husky_sensor_config_1/test_gimbal.sh
The gimbal motion is controlled using a velocity controller again. Internally, we're using force commands, so joint limits are enforced.
> Restoring velocity controller for moving gimbals

- subt_ign/src/CommsBrokerPlugin.cc
Together with https://github.com/ignition-tooling/release-tools/pull/257 (already enabled today) should produce a green CI
> Fix warning produced by CI in CommsBrokerPlugin

- submitted_models/ctu_cras_norlab_absolem_sensor_config_1/model.sdf
**Previous view:**
**New alignment:**
**New view:**
> Moved and realigned RGBD camera to not be obstructed by realsense mesh

- subt_ign/src/GameLogicPlugin.cc
Record marsupial pairs in the summary.yaml file.
> Record marsupial pairs

- submitted_models/cerberus_m100_sensor_config_1/launch/spawner.rb
- submitted_models/cerberus_m100_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_qav500_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/robotika_freyja_sensor_config_1/launch/vehicle_topics.launch
Added a few missing optical frames, and removed the extra rgbd parameters from cerberus_m100
> Fix optical frames for cerberus_m100, marble_qav500, robotika_freyja

- subt_ign/launch/cave_circuit.ign
- subt_ign/launch/cloudsim_sim.ign
- subt_ign/launch/competition.ign
- subt_ign/launch/tunnel_circuit_practice.ign
- subt_ign/launch/urban_circuit.ign
Rotate child models to face backward for some marsupial parents.
> Rotate marsupials

- subt_ign/include/subt_ign/CommonTypes.hh
- subt_ign/src/GameLogicPlugin.cc
Fix an error in the event stream, and also improve the artifact report events
The matches the event stream modification in pull request #545.
> Fix event stream.

- subt_ign/worlds/niosh_ex_config_a.sdf
- subt_ign/worlds/niosh_ex_config_b.sdf
- subt_ign/worlds/niosh_sr_config_a.sdf
- subt_ign/worlds/niosh_sr_config_b.sdf
Since we're not dynamically generating worlds with different light configurations for NIOSH worlds, I added the lights directly to the world files. 
> Add lights to NIOSH SR and EX worlds

- subt_ign/src/GameLogicPlugin.cc
Adding duplicate and unknown artifact reports to `events.yml`.
> Log duplicate artifact report and unknown artifact reports

- submitted_models/robotika_freyja_sensor_config_1/model.sdf
The lights unfortunately pointed to the ground - fixed now.
thanks
Martin/Robotika Team
> fix direction of lights on robot robotika/Freyja

- subt_ign/launch/validate_artifacts.ign
- subt_ign/launch/validate_connections.ign
- subt_ign/src/ArtifactValidator.cc
Fix path issues with validators.
> Connection and artifact validator fixes

- docker/cloudsim_sim/Dockerfile
> Add xvfb to sim image

- subt_ign/worlds/urban_qual.sdf
> Fix phone under mesh in urban qual

- docker/cloudsim_bridge/Dockerfile
- docker/cloudsim_sim/Dockerfile
- docker/subt_shell/Dockerfile
- docker/subt_sim_entry/Dockerfile
- docker/subt_team_entry/Dockerfile
- subt-communication/subt_communication_model/src/subt_communication_model.cpp
- subt-communication/subt_rf_interface/include/subt_rf_interface/subt_rf_model.h
- subt-communication/subt_rf_interface/src/subt_rf_model.cpp
- subt_ign/CMakeLists.txt
- subt_ign/include/subt_ign/CommonTypes.hh
- subt_ign/include/subt_ign/VisibilityTable.hh
- subt_ign/include/subt_ign/VisibilityTypes.hh
- subt_ign/launch/cave_circuit.ign
- subt_ign/package.xml
- subt_ign/src/CommsBrokerPlugin.cc
- subt_ign/src/VisibilityPlugin.cc
- subt_ign/src/VisibilityRfModel.cc
- subt_ign/src/VisibilityTable.cc
- subt_ign/src/ign_to_fcl.cc
- subt_ign/src/ign_to_fcl.hh
- subt_ign/src/validate_visibility_table.cc
- subt_ign/src/world_generator_cave.cc
> Merge from master

- subt_ign/launch/cave_circuit.ign
- subt_ign/launch/cloudsim_sim.ign
- subt_ign/launch/competition.ign
- subt_ign/launch/tunnel_circuit_practice.ign
- subt_ign/launch/urban_circuit.ign
This change is needed for cave practice world 02.
> Add helmet_5 to launch files

- submitted_models/marble_qav500_sensor_config_1/launch/vehicle_topics.launch
This removes duplicate topics from the Marble Qav500 model.
> Remove duplicate topics from Marble Qav500

- subt_ign/src/VisibilityPlugin.cc
For the `level_generator` to work properly, it's important that it is ran with the maximum tile dimensions as parameters. This PR adds code to `VisibilityPlugin.cc` to print out the maximum tile dimensions right before generating the visibility LUT. 
To use it, run `ign launch visibility.ign circuit:=<circuit> worldName=:=<world name>`.
> Print maximum tile dimensions in each axis

- subt_ign/src/GameLogicPlugin.cc
Off by one error in the calculation.
> Fix mean time calculation

- subt_ign/launch/cave_circuit.ign
- subt_ign/launch/cloudsim_sim.ign
- subt_ign/launch/competition.ign
- subt_ign/launch/tunnel_circuit_practice.ign
- subt_ign/launch/urban_circuit.ign
Utilize robot offsets when placing the teambase. Fixes issue #690.
> Fix issue #690

- submitted_models/cerberus_rmf_sensor_config_1/launch/vehicle_topics.launch
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Enhancements to #722

- docker/cloudsim_bridge/Dockerfile
- docker/cloudsim_sim/Dockerfile
- docker/subt_shell/Dockerfile
- docker/subt_sim_entry/Dockerfile
- docker/subt_team_entry/Dockerfile
> Update to pr #688

- submitted_models/cerberus_anymal_c_sensor_config_1/model.sdf
- submitted_models/costar_shafter_sensor_config_1/model.sdf
> Updates to lidar models on new robot models

- docker/subt_sim_entry/Dockerfile
> Fix dockerfile github branch

- subt_ign/src/GameLogicPlugin.cc
The goal is to make it a little easier to debug the shutdown process.
> Added more logging to the shutdown process

- subt_ign/src/Common.cc
- subt_ign/src/VisibilityTable.cc
Fixes finding files using the `FullWorldPath` function.
> Fix finding worlds

- submitted_models/cerberus_anymal_b_sensor_config_1/model.sdf
- submitted_models/cerberus_m100_sensor_config_1/model.sdf
- submitted_models/costar_husky_sensor_config_1/model.sdf
- submitted_models/costar_husky_sensor_config_2/model.sdf
- submitted_models/explorer_ds1_sensor_config_1/model.sdf
- submitted_models/explorer_r2_sensor_config_1/model.sdf
- submitted_models/explorer_x1_sensor_config_1/model.sdf
- submitted_models/explorer_x1_sensor_config_2/model.sdf
- submitted_models/ssci_x4_sensor_config_1/model.sdf
- submitted_models/x1_sensor_config_6/model.sdf
- submitted_models/x2_sensor_config_7/model.sdf
Adjusts resolution value in order to support point cloud noise: https://github.com/ignitionrobotics/ign-sensors/pull/86
> Fix lidar resolution value

- subt_ign/scripts/subt_docker.bash
Updates aws account number in subt_docker.bash
> Update aws account number in script

- subt_ign/scripts/subt_docker_list.bash
- subt_ign/scripts/subt_docker_uri.bash
Fix the AWS account number in the remaining scripts
> AWS account number update

- submitted_models/cerberus_anymal_b_sensor_config_1/model.sdf
- submitted_models/cerberus_anymal_c_sensor_config_1/model.sdf
- submitted_models/cerberus_m100_sensor_config_1/model.sdf
- submitted_models/cerberus_m100_sensor_config_1/model_package.sdf
- submitted_models/costar_husky_sensor_config_1/model.sdf
- submitted_models/costar_husky_sensor_config_2/model.sdf
- submitted_models/costar_shafter_sensor_config_1/model.sdf
- submitted_models/marble_hd2_sensor_config_1/model.sdf
- submitted_models/marble_husky_sensor_config_1/model.sdf
- submitted_models/marble_qav500_sensor_config_1/model.sdf
- submitted_models/marble_qav500_sensor_config_1/model_package.sdf
- submitted_models/ssci_x4_sensor_config_1/model.sdf
- submitted_models/ssci_x4_sensor_config_1/model_package.sdf
- submitted_models/x1_sensor_config_6/model.sdf
- submitted_models/x1_sensor_config_6/model_package.sdf
- submitted_models/x2_sensor_config_7/model.sdf
> Fix PI issue 804

- subt_ros/launch/models_common/all_robots.launch
- subt_ros/launch/models_common/all_uavs.launch
- subt_ros/launch/models_common/all_ugvs.launch
- subt_ros/launch/models_common/breadcrumbs.launch
- subt_ros/launch/models_common/imu.launch
- subt_ros/launch/models_common/lidar_2d.launch
- subt_ros/launch/models_common/lidar_3d.launch
- subt_ros/launch/models_common/rgb_camera.launch
- subt_ros/launch/models_common/rgbd_camera.launch
- subt_ros/launch/models_common/thermal_camera.launch
This is a set of helpers that aim at simplifying vehicle_topics.launch of robot models and making these files better maintainable. This PR itself doesn't change anything in the way the robots run the bridge nodes, but it adds opportunity for either new model creators or for existing model authors to greatly simplify the code and future-proof it.
Here's an example roslaunch that makes heavy use of the proposed feature. It is a robot with 7 cameras and a 3D lidar, and the whole vehicle_topics.launch file is just 128 lines.
<details>
```
<?xml version="1.0"?>
<launch>
<env name="IGN_TRANSPORT_TOPIC_STATISTICS" value="1"/>
<arg name="world_name"/>
<arg name="name"/>
<arg name="breadcrumbs" default="0"/>
<arg name="has_omnicam_vras" default="1"/>
<arg name="has_ouster_lidar" default="1"/>
<arg …
```
> Add a library of roslaunch helpers for vehicle_topics.launch

- subt_ign/worlds/finals_practice_01.sdf
- subt_ign/worlds/tunnel_circuit/05/tunnel_circuit_05.sdf
* Added rails to sections of Finals PW1
* Adjusted phones in Tunnel 5
> Tunnel mods

- submitted_models/explorer_r3_sensor_config_1/specifications.md
Follow up for https://github.com/osrf/subt/pull/784#issuecomment-782749693
> Validation Data for R3

- submitted_models/emesent_hovermap_sensor_config_1/CMakeLists.txt
Our build fails with the line I deleted in this PR.
> Fix CMakeLists in emesent UAV

- submitted_models/ctu_cras_norlab_x500_sensor_config_1/model.sdf
There was a missing zero in the sensor pose.
> Fixes pose of rs_up, rs_down rgbd cameras of x500 UAV

- submitted_models/ctu_cras_norlab_x500_sensor_config_1/model.sdf
This issue was correctly pointed out in https://github.com/osrf/subt/issues/902.
> fixed fx, fy focal length of front camera to be consistent with hfov

- submitted_models/coro_allie_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_jeanine_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_mike_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/ctu_cras_norlab_spot_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/explorer_r3_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_husky_sensor_config_6/launch/vehicle_topics.launch
- submitted_models/marble_spot_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_spot_sensor_config_2/launch/vehicle_topics.launch
Added missing "IGN_TRANSPORT_TOPIC_STATISTICS" to launch files.
> Update vehicle launch files

- subt_ign/include/subt_ign/RobotPlatformTypes.hh
- subt_ign/launch/cloudsim_sim.ign
- subt_ign/launch/competition.ign
To test:
```
ign launch cloudsim_sim.ign worldName:=simple_cave_01 circuit:=cave robotName1:=X1 robotConfig1:=CORO_JEANINE_SENSOR_CONFIG_2 robotName2:=X2 robotConfig2:=CORO_PAM_SENSOR_CONFIG_1 marsupial1:=X1:X2
```
> Adding marsupial capabilities to jeanine

- submitted_models/csiro_data61_dtr_sensor_config_1/model.sdf
> Add camera intrinsics of DTR

- subt_ign/worlds/finals_practice_01.sdf
Swapped a rock fall for a wall obstacle.
1. `ign launch cloudsim_sim.ign worldName:=finals_practic01 circuit:=finals robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1`
2. `ign service -s /world/finals_practice_01/set_pose /set_pose --reqtype ignition.msgs.Pose --reptype ignition.msgs.Boolean --timeout 300 --req 'name: "X1", position {x:22 y:16 z:1}, orientation {z:0.707 w:0.707}'`
> Added wall obstacle finals practice 1

- submitted_models/marble_husky_sensor_config_5/model.sdf
- submitted_models/marble_husky_sensor_config_5/urdf/robot_from_sdf.xacro
Resolves Issue #928.
To test:
1. `ign launch competition.ign worldName:=simple_cave_01 circuit:=cave robotName1:=X1 robotConfig1:=MARBLE_HUSKY_SENSOR_CONFIG_5`
2. `rosrun rviz rviz` then visualize the `RobotModel`
> Fix marble husky 5 visualization

- subt_ign/include/subt_ign/RobotPlatformTypes.hh
Fixes one of the issues discovered on #936 .
> Added Marmotte robot type

- docker/cloudsim_bridge/Dockerfile
- docker/cloudsim_bridge/run_bridge.bash
- docker/cloudsim_sim/Dockerfile
- docker/cloudsim_sim/run_sim.bash
> Added unbuffer to the bridge and sim launch commands

- subt_ign/src/GameLogicPlugin.cc
Adds additional information to collision logging.
> Additional collision logging

- submitted_models/cerberus_gagarin_sensor_config_1/model.sdf
- submitted_models/marble_husky_sensor_config_1/model.sdf
- submitted_models/marble_husky_sensor_config_1/specifications.md
- submitted_models/marble_husky_sensor_config_3/model.sdf
- submitted_models/marble_husky_sensor_config_4/model.sdf
- submitted_models/marble_qav500_sensor_config_1/model.sdf
**Includes:**
- Documentation cleanup on MARBLE Husky SC1
- LIDAR parameter adjustments/fixes on MARBLE Husky SC1, SC3, and SC4
- PicoFlexx intrinsic parameters on CERBERUS Gagarin and MARBLE QAV500 models
> Miscellaneous Fixes for Submitted Models

- submitted_models/coro_mike_sensor_config_1/launch/spawner.rb
- submitted_models/coro_mike_sensor_config_1/model.sdf
- submitted_models/coro_mike_sensor_config_1/specifications.md
- submitted_models/coro_mike_sensor_config_1/urdf/model.xacro
- submitted_models/coro_mike_sensor_config_2/launch/spawner.rb
Updates for Mike based on validation results.
> Updated based on validation tests

- submitted_models/coro_allie_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_crystal_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_jeanine_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_karen_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_mike_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_pam_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_rocky_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/coro_rocky_sensor_config_3/launch/vehicle_topics.launch
- submitted_models/ctu_cras_norlab_spot_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/ctu_cras_norlab_x500_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/emesent_hovermap_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_husky_sensor_config_5/launch/vehicle_topics.launch
- submitted_models/marble_spot_sensor_config_1/launch/vehicle_topics.launch
- submitted_models/marble_spot_sensor_config_2/launch/vehicle_topics.launch
- subt_ros/launch/teambase_topics.launch
Added missing mapping server relays.
> Add mapping server relays to models and teambase

- subt_ign/worlds/final_prelim/01/final_prelim_01.sdf
> Fix gas artifact and move debris wall 2
